# Generated by Django 5.2 on 2025-06-05 20:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitegroup',
            name='owner',
        ),
        migrations.AddField(
            model_name='sitegroup',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitegroup',
            name='owners',
            field=models.ManyToManyField(blank=True, null=True, related_name='group_ownerships', to=settings.AUTH_USER_MODEL),
        ),
    ]
