# Generated by Django 5.2 on 2025-06-05 21:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_remove_sitegroup_owner_sitegroup_members_and_more'),
        ('tableviewer', '0017_remove_dynamictable_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitegroup',
            options={'ordering': ['name'], 'verbose_name': 'Site Group', 'verbose_name_plural': 'Site Groups'},
        ),
        migrations.AddField(
            model_name='sitegroup',
            name='tables',
            field=models.ManyToManyField(blank=True, related_name='group_tables', to='tableviewer.dynamictable'),
        ),
        migrations.AlterField(
            model_name='sitegroup',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitegroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitegroup',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='group_ownerships', to=settings.AUTH_USER_MODEL),
        ),
    ]
