# Generated by Django 5.2 on 2025-04-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablecolumn',
            name='use_column',
            field=models.BooleanField(default=True),
        ),
    ]
