# Generated by Django 5.2 on 2025-05-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableviewer', '0002_tablecolumn_use_column'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamictable',
            options={'ordering': ('id',), 'verbose_name': 'Dynamic Table', 'verbose_name_plural': 'Dynamic Tables'},
        ),
        migrations.AlterModelOptions(
            name='tablecolumn',
            options={'ordering': ['order'], 'verbose_name': 'Table Column', 'verbose_name_plural': 'Table Columns'},
        ),
        migrations.AddField(
            model_name='dynamictable',
            name='results_shown',
            field=models.IntegerField(default=5, help_text='Number of results shown in the table'),
        ),
    ]
