# Generated by Django 5.2 on 2025-05-15 22:29

import ckeditor.fields
import django.db.models.deletion
import tableviewer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableviewer', '0003_alter_dynamictable_options_alter_tablecolumn_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamictable',
            name='after_table_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Text after the table'),
        ),
        migrations.AddField(
            model_name='dynamictable',
            name='before_table_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Text before the table'),
        ),
        migrations.AddField(
            model_name='dynamictable',
            name='logo',
            field=models.ImageField(blank=True, upload_to=tableviewer.models.logo_directory_path),
        ),
        migrations.AddField(
            model_name='dynamictable',
            name='logo_placement',
            field=models.CharField(blank=True, choices=[('left', 'left'), ('right', 'right'), ('center', 'center')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tablecolumn',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='columns', to='tableviewer.dynamictable'),
        ),
    ]
