# Generated by Django 5.2 on 2025-05-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableviewer', '0004_dynamictable_after_table_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamictable',
            name='logo_placement',
            field=models.CharField(choices=[('left', 'left'), ('right', 'right'), ('center', 'center')], default='left', max_length=255),
        ),
    ]
