# Generated by Django 5.2 on 2025-05-15 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableviewer', '0005_alter_dynamictable_logo_placement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamictable',
            name='logo_placement',
        ),
    ]
