# Generated by Django 5.2 on 2025-05-20 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableviewer', '0006_remove_dynamictable_logo_placement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablerow',
            name='table',
        ),
        migrations.AddField(
            model_name='dynamictable',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='URLShortcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(help_text='No spaces are allowed; if spaces are needed, please use dashes or underscores, instead.', max_length=100, unique=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shortcuts', to='tableviewer.dynamictable')),
            ],
        ),
        migrations.DeleteModel(
            name='TableCell',
        ),
        migrations.DeleteModel(
            name='TableRow',
        ),
    ]
