# Generated by Django 5.2 on 2025-05-20 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableviewer', '0007_remove_tablerow_table_dynamictable_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlshortcut',
            options={'ordering': ['id'], 'verbose_name': 'URL Shortcut', 'verbose_name_plural': 'URL Shortcuts'},
        ),
    ]
