# Generated by Django 5.2 on 2025-05-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableviewer', '0008_alter_urlshortcut_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortcut',
            name='url',
            field=models.CharField(help_text='No spaces are allowed; if spaces are needed, please use dashes or underscores, instead.', max_length=100, unique=True),
        ),
    ]
