# Generated by Django 5.2 on 2025-05-21 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableviewer', '0009_alter_urlshortcut_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablecolumn',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='tableviewer.dynamictable'),
        ),
    ]
