# Generated by Django 5.2 on 2025-05-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('tableviewer', '0011_alter_urlshortcut_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamictable',
            name='groups',
            field=models.ManyToManyField(blank=True, to='administration.sitegroup'),
        ),
    ]
