# Generated by Django 5.2 on 2025-05-22 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableviewer', '0012_dynamictable_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamictable',
            name='published',
        ),
        migrations.CreateModel(
            name='TableSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tableviewer.dynamictable')),
            ],
        ),
    ]
