# Generated by Django 5.2 on 2025-05-22 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableviewer', '0013_remove_dynamictable_published_tablesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablesettings',
            name='table',
        ),
        migrations.AddField(
            model_name='dynamictable',
            name='settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tableviewer.tablesettings'),
        ),
    ]
