# Generated by Django 5.2 on 2025-05-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableviewer', '0014_remove_tablesettings_table_dynamictable_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesettings',
            name='name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
