# Generated by Django 5.2 on 2025-05-22 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableviewer', '0015_tablesettings_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablesettings',
            options={'verbose_name': 'Table Settings', 'verbose_name_plural': 'Table Settings'},
        ),
    ]
