# Generated by Django 5.2 on 2025-06-05 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableviewer', '0016_alter_tablesettings_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamictable',
            name='groups',
        ),
    ]
